### ISSUE TITLE
Hi from London

### ISSUE THREAD

**Issue by scheung38** [joppa27/dockerfiles#1]
Hi joppa27,

I am also relatively new to Docker. Are you saying that from within docker terminal:

$docker pull  kongkoro/pycharm

and then

$ docker run -it -v /tmp/.X11-unix/:/tmp/.X11-unix/ -v ~/PycharmProjects:/root/PycharmProjects -v ~/.PyCharm40:/root/.PyCharm40 -e DISPLAY=$DISPLAY --rm kongkoro/pycharm

I will be able to run Pycharm within your container?

Awesome if so but after the following:

$ docker run -it -v /tmp/.X11-unix/:/tmp/.X11-unix/ -v ~/PycharmProjects:/root/PycharmProjects -v ~/.PyCharm40:/root/.PyCharm40 -e DISPLAY=$DISPLAY --rm kongkoro/pycharm

I get:

Start Failed: Internal error. Please report to https://youtrack.jetbrains.com

java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.ide.Bootstrap.main(Bootstrap.java:39)
    at com.intellij.idea.Main.main(Main.java:84)
Caused by: java.lang.InternalError: Can't connect to X11 window server using '/private/tmp/com.apple.launchd.C5NUSdYyJB/org.macosforge.xquartz:0' as the value of t
    at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
    at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
    at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:110)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:191)
    at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:102)
    at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:81)
    at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:120)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:191)
    at java.awt.Toolkit$2.run(Toolkit.java:869)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:861)
    at java.awt.Toolkit.getEventQueue(Toolkit.java:1756)
    at java.awt.EventQueue.isDispatchThread(EventQueue.java:1025)
    at javax.swing.SwingUtilities.isEventDispatchThread(SwingUtilities.java:1360)
    at javax.swing.text.StyleContext.reclaim(StyleContext.java:454)
    at javax.swing.text.StyleContext.addAttribute(StyleContext.java:311)
    at javax.swing.text.html.StyleSheet.addAttribute(StyleSheet.java:578)
    at javax.swing.text.StyleContext$NamedStyle.addAttribute(StyleContext.java:1501)
    at javax.swing.text.StyleContext$NamedStyle.setName(StyleContext.java:1312)
    at javax.swing.text.StyleContext$NamedStyle.<init>(StyleContext.java:1259)
    at javax.swing.text.StyleContext.addStyle(StyleContext.java:107)
    at javax.swing.text.StyleContext.<init>(StyleContext.java:87)
    at javax.swing.text.html.StyleSheet.<init>(StyleSheet.java:166)
    at javax.swing.text.html.HTMLEditorKit.getStyleSheet(HTMLEditorKit.java:392)
    at com.intellij.util.ui.UIUtil.<clinit>(UIUtil.java:97)
    at com.intellij.ide.plugins.PluginManager.start(PluginManager.java:71)
    ... 6 more

Also, an UI exception occurred on attempt to show above message:
java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11GraphicsEnvironment
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:191)
    at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:102)
    at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:81)
    at javax.swing.RepaintManager.<clinit>(RepaintManager.java:212)
    at javax.swing.JComponent.repaint(JComponent.java:4796)
    at java.awt.Component.repaint(Component.java:3297)
    at javax.swing.text.JTextComponent.setEditable(JTextComponent.java:1807)
    at javax.swing.text.JTextComponent.<init>(JTextComponent.java:319)
    at javax.swing.JEditorPane.<init>(JEditorPane.java:197)
    at javax.swing.JTextPane.<init>(JTextPane.java:90)
    at com.intellij.idea.Main.showMessage(Main.java:280)
    at com.intellij.idea.Main.showMessage(Main.java:266)
    at com.intellij.idea.Main.main(Main.java:87)

Not sure what happened there?

Similarly:

$ docker run -it -v /tmp/.X11-unix/:/tmp/.X11-unix/ -e DISPLAY=$DISPLAY --rm kongkoro/pycharm

Start Failed: Internal error. Please report to https://youtrack.jetbrains.com

java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.ide.Bootstrap.main(Bootstrap.java:39)
    at com.intellij.idea.Main.main(Main.java:84)
Caused by: java.lang.InternalError: Can't connect to X11 window server using '/private/tmp/com.apple.launchd.C5NUSdYyJB/org.macosforge.xquartz:0' as the value of t
    at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
    at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
    at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:110)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:191)
    at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:102)
    at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:81)
    at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:120)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:191)
    at java.awt.Toolkit$2.run(Toolkit.java:869)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:861)
    at java.awt.Toolkit.getEventQueue(Toolkit.java:1756)
    at java.awt.EventQueue.isDispatchThread(EventQueue.java:1025)
    at javax.swing.SwingUtilities.isEventDispatchThread(SwingUtilities.java:1360)
    at javax.swing.text.StyleContext.reclaim(StyleContext.java:454)
    at javax.swing.text.StyleContext.addAttribute(StyleContext.java:311)
    at javax.swing.text.html.StyleSheet.addAttribute(StyleSheet.java:578)
    at javax.swing.text.StyleContext$NamedStyle.addAttribute(StyleContext.java:1501)
    at javax.swing.text.StyleContext$NamedStyle.setName(StyleContext.java:1312)
    at javax.swing.text.StyleContext$NamedStyle.<init>(StyleContext.java:1259)
    at javax.swing.text.StyleContext.addStyle(StyleContext.java:107)
    at javax.swing.text.StyleContext.<init>(StyleContext.java:87)
    at javax.swing.text.html.StyleSheet.<init>(StyleSheet.java:166)
    at javax.swing.text.html.HTMLEditorKit.getStyleSheet(HTMLEditorKit.java:392)
    at com.intellij.util.ui.UIUtil.<clinit>(UIUtil.java:97)
    at com.intellij.ide.plugins.PluginManager.start(PluginManager.java:71)
    ... 6 more

Also, an UI exception occurred on attempt to show above message:
java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11GraphicsEnvironment
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:191)
    at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:102)
    at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:81)
    at javax.swing.RepaintManager.<clinit>(RepaintManager.java:212)
    at javax.swing.JComponent.repaint(JComponent.java:4796)
    at java.awt.Component.repaint(Component.java:3297)
    at javax.swing.text.JTextComponent.setEditable(JTextComponent.java:1807)
    at javax.swing.text.JTextComponent.<init>(JTextComponent.java:319)
    at javax.swing.JEditorPane.<init>(JEditorPane.java:197)
    at javax.swing.JTextPane.<init>(JTextPane.java:90)
    at com.intellij.idea.Main.showMessage(Main.java:280)
    at com.intellij.idea.Main.showMessage(Main.java:266)
    at com.intellij.idea.Main.main(Main.java:87)

I do have evaluation copy of Pycharm Professional 2016.1 on my Mac if that helps.

then trying to build it locally with your Dockerfile:

FROM debian:wheezy
MAINTAINER Idi Eradiri ieradiri@gmail.com
# docker run -it -v /tmp/.X11-unix/:/tmp/.X11-unix/ -e DISPLAY=$DISPLAY --rm kongkoro/pycharm

ENV PYCHARM_HOME=/etc/pycharm
RUN apt-get update &&\
    apt-get install -y \
    wget \
    git \
    openjdk-7-jre \
    libxrender1 \
    libxtst6 \
    python \
    --no-install-recommends &&\
    wget -P /tmp/ http://download.jetbrains.com/python/pycharm-community-4.5.4.tar.gz &&\
    mkdir ${PYCHARM_HOME} && tar -xzvf /tmp/pycharm-community-4.5.4.tar.gz -C ${PYCHARM_HOME} --strip=1 &&\
    wget -P /tmp/ https://bootstrap.pypa.io/get-pip.py && python /tmp/get-pip.py &&\
    rm -rf /var/lib/apt-lists; rm -rf /tmp/*; apt-get purge wget -y; apt-get autoremove -y

ENTRYPOINT ["/etc/pycharm/bin/pycharm.sh"]

$ docker build -t kongkoro/pycharm .

Error checking context: 'no permission to read from '/Users/seb/.rnd''

Seb

**Comment by joppa27** [comment]
Thanks for taking my pycharm container for a spin! It has been a while since I've played around with this container, but I'll see if I can help.  One quick question is which OS are you using? if you're using OSX you're going to have to do a hacky workaround to get this to work.

This blog-post explains how the process works in general & I think there's a link in that post to a method you can use to run the container in OSX
https://blog.jessfraz.com/post/docker-containers-on-the-desktop/

I would recommend using the container in ubuntu. This container was desinged to be run in Linux, it's sooooooo much easier because you can mount the X11 socket in Linux.

Running the container in OSX isn't impossible, but it's not trivial either.
